version: '3.9'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: moment082
      MYSQL_DATABASE: file
      MYSQL_USER: moment
      MYSQL_PASSWORD: moment
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    environment:
      - REDIS_PASSWORD=moment
    command: redis-server --requirepass moment
    volumes:
      - redis-data:/data
    restart: always

volumes:
  mysql-data:
  redis-data:
